# Generated by Django 5.2.16 on 2026-07-19 08:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight line'), ('reducing_balance', 'Reducing balance')], default='straight_line', max_length=20)),
                ('useful_life_months', models.PositiveIntegerField(default=60)),
                ('residual_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('annual_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('accum_depr_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
                ('depr_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name_plural': 'Asset categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('custodian', models.CharField(blank=True, max_length=100)),
                ('acquisition_date', models.DateField()),
                ('in_service_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cost_base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('depreciation_method', models.CharField(blank=True, choices=[('straight_line', 'Straight line'), ('reducing_balance', 'Reducing balance')], max_length=20)),
                ('useful_life_months', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('fully_depreciated', 'Fully depreciated'), ('disposed', 'Disposed'), ('written_off', 'Written off')], db_index=True, default='active', max_length=20)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capitalization_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal')),
                ('disposal_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('accumulated_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('nbv_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='assets.asset')),
            ],
            options={
                'verbose_name_plural': 'Depreciation entries',
                'ordering': ['asset__code'],
            },
        ),
    ]
