# Generated by Django 5.2.16 on 2026-07-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depreciationrun',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='depreciationrun',
            name='period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_run', to='accounting.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='assets.depreciationrun'),
        ),
    ]
