# Generated by Django 5.2.16 on 2026-07-19 08:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consumption_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name_plural': 'Item categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('uom', models.CharField(default='each', max_length=20)),
                ('item_type', models.CharField(choices=[('stockable', 'Stockable'), ('consumable', 'Consumable'), ('service', 'Service')], default='stockable', max_length=12)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemcategory')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('storekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('move_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_cost_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('posted', 'Posted')], default='posted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.item')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal')),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_out', to='inventory.warehouse')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['item', 'date'], name='inventory_s_item_id_ae71d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
