# Generated by Django 5.2.16 on 2026-07-31 08:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_permissions'),
        ('inventory', '0003_tenancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reorder_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='item',
            name='track_lots',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StockRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('partially_issued', 'Partially issued')], db_index=True, default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='inventory.department')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='core.school')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.DecimalField(decimal_places=2, max_digits=18)),
                ('qty_approved', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('qty_issued', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockrequisition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=60)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.item')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='core.school')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
                'indexes': [models.Index(fields=['item', 'warehouse', 'expiry_date'], name='inventory_s_item_id_13446a_idx')],
                'unique_together': {('item', 'warehouse', 'lot_code')},
            },
        ),
        migrations.AddIndex(
            model_name='stockrequisition',
            index=models.Index(fields=['status', 'school'], name='inventory_s_status_c90948_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockrequisition',
            unique_together={('school', 'number')},
        ),
    ]
