# Generated by Django 5.2.16 on 2026-07-19 08:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('ar_control', 'Accounts receivable control'), ('ap_control', 'Accounts payable control'), ('deferred_fee_income', 'Deferred fee income'), ('grni', 'Goods received not invoiced'), ('inventory_adjustment', 'Inventory adjustment'), ('bursary_contra', 'Bursaries / scholarships contra'), ('fx_gain_realized', 'Realized FX gain'), ('fx_loss_realized', 'Realized FX loss'), ('fx_gain_unrealized', 'Unrealized FX gain'), ('fx_loss_unrealized', 'Unrealized FX loss'), ('gain_on_disposal', 'Gain on asset disposal'), ('loss_on_disposal', 'Loss on asset disposal'), ('opening_balances', 'Opening balances contra'), ('accumulated_fund', 'Accumulated fund'), ('vat_payable', 'VAT payable'), ('rounding', 'Rounding differences')], max_length=30)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
            ],
            options={
                'ordering': ['purpose', 'currency'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], default='bank', max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('book_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_reconciled_date', models.DateField(blank=True, null=True)),
                ('last_reconciled_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('file', models.FileField(blank=True, null=True, upload_to='bank_statements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('disputed', 'Disputed')], default='unmatched', max_length=10)),
                ('ai_match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_match_suggestion', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=10)),
                ('account_subtype', models.CharField(max_length=30)),
                ('report_group', models.CharField(choices=[('current_assets', 'Current Assets'), ('non_current_assets', 'Non-current Assets'), ('current_liabilities', 'Current Liabilities'), ('non_current_liabilities', 'Non-current Liabilities'), ('equity', 'Accumulated Fund / Equity'), ('fee_income', 'Fee Income'), ('other_income', 'Other Income'), ('operating_expenses', 'Operating Expenses'), ('administrative_expenses', 'Administrative Expenses'), ('finance_costs', 'Finance Costs')], max_length=30)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_manual_journal', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('effective_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_no', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('debit_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('journal_type', models.CharField(choices=[('general', 'General'), ('sales', 'Sales'), ('receipts', 'Receipts'), ('payments', 'Payments'), ('purchases', 'Purchases'), ('inventory', 'Inventory'), ('depreciation', 'Depreciation'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('opening', 'Opening')], default='general', max_length=15)),
                ('date', models.DateField(db_index=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('reversal_reason', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=50)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('debit_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('debit', 'Debit target account'), ('credit', 'Credit target account')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ticked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('party_type', models.CharField(choices=[('student', 'Student'), ('supplier', 'Supplier')], max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('contra_account', models.CharField(blank=True, max_length=10)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.bankaccount')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
