# Generated by Django 5.2.16 on 2026-07-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('procurement', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='accounting.chartofaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'effective_date')},
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='reversed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='journal_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entry', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_journal_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.student'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='target_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='journal_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='students.student'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='sub_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.subaccount'),
        ),
        migrations.AddField(
            model_name='subaccounttransaction',
            name='journal_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_transactions', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='subaccounttransaction',
            name='sub_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounting.subaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='accountmapping',
            unique_together={('purpose', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('fiscal_year', 'period_no')},
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['status', 'date'], name='accounting__status_700391_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__7e9759_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['account', 'date'], name='accounting__account_9a32f6_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['currency', 'date'], name='accounting__currenc_c6cddb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationitem',
            unique_together={('reconciliation', 'journal_line')},
        ),
        migrations.AddIndex(
            model_name='subaccount',
            index=models.Index(fields=['party_type', 'category', 'currency'], name='accounting__party_t_0af344_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subaccount',
            unique_together={('student', 'category', 'currency'), ('supplier', 'category', 'currency')},
        ),
        migrations.AddIndex(
            model_name='subaccounttransaction',
            index=models.Index(fields=['sub_account', 'date'], name='accounting__sub_acc_c36c2d_idx'),
        ),
    ]
