# Generated by Django 5.2.16 on 2026-07-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_tenancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapping',
            name='purpose',
            field=models.CharField(choices=[('ar_control', 'Accounts receivable control'), ('ap_control', 'Accounts payable control'), ('deferred_fee_income', 'Deferred fee income'), ('grni', 'Goods received not invoiced'), ('inventory_adjustment', 'Inventory adjustment'), ('bursary_contra', 'Bursaries / scholarships contra'), ('fx_gain_realized', 'Realized FX gain'), ('fx_loss_realized', 'Realized FX loss'), ('fx_gain_unrealized', 'Unrealized FX gain'), ('fx_loss_unrealized', 'Unrealized FX loss'), ('gain_on_disposal', 'Gain on asset disposal'), ('loss_on_disposal', 'Loss on asset disposal'), ('opening_balances', 'Opening balances contra'), ('accumulated_fund', 'Accumulated fund'), ('vat_payable', 'VAT payable'), ('rounding', 'Rounding differences'), ('interschool_due_from', 'Due from related schools'), ('interschool_due_to', 'Due to related schools')], max_length=30),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.CharField(choices=[('general', 'General'), ('sales', 'Sales'), ('receipts', 'Receipts'), ('payments', 'Payments'), ('purchases', 'Purchases'), ('inventory', 'Inventory'), ('depreciation', 'Depreciation'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('opening', 'Opening'), ('transfer', 'Inter-school transfer')], default='general', max_length=15),
        ),
    ]
