# Generated by Django 5.2.16 on 2026-07-31 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('bursar', 'Bursar'), ('accounts_clerk', 'Accounts Clerk'), ('head', 'Head of School'), ('storekeeper', 'Storekeeper'), ('teacher', 'Teacher'), ('auditor_readonly', 'Auditor (read-only)'), ('guardian_portal', 'Guardian (portal)'), ('student_portal', 'Student (portal)')], max_length=30)),
                ('module', models.CharField(choices=[('accounting', 'Accounting'), ('fees', 'Fees'), ('students', 'Students'), ('attendance', 'Attendance'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('assets', 'Assets'), ('ingestion', 'Document Ingestion'), ('reports', 'Reports'), ('settings', 'Settings'), ('users', 'Users & Permissions')], max_length=20)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('post', 'Post'), ('approve', 'Approve'), ('export', 'Export')], max_length=20)),
                ('allowed', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.school')),
            ],
            options={
                'ordering': ['school', 'role', 'module', 'action'],
                'indexes': [models.Index(fields=['school', 'role'], name='core_rolepe_school__ee1106_idx')],
                'unique_together': {('school', 'role', 'module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('accounting', 'Accounting'), ('fees', 'Fees'), ('students', 'Students'), ('attendance', 'Attendance'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('assets', 'Assets'), ('ingestion', 'Document Ingestion'), ('reports', 'Reports'), ('settings', 'Settings'), ('users', 'Users & Permissions')], max_length=20)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('post', 'Post'), ('approve', 'Approve'), ('export', 'Export')], max_length=20)),
                ('allowed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'module', 'action'],
                'unique_together': {('user', 'module', 'action')},
            },
        ),
    ]
