# Generated by Django 5.2.16 on 2026-07-19 08:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewed', 'Previewed'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('invoices_created', models.PositiveIntegerField(default=0)),
                ('total_billed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grades', models.ManyToManyField(blank=True, to='students.grade')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_runs', to='students.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(max_length=500)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('pocket_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deferred_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name_plural': 'Fee categories',
                'ordering': ['pocket_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fees.creditnote')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fees.feecategory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BursaryAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('funder', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='students.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.term')),
                ('fee_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.feecategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='fees.billingrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_invoices', to='students.enrollment')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_invoices', to='students.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_invoices', to='students.term')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='fees.feeinvoice'),
        ),
        migrations.CreateModel(
            name='FeeInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('bursary_award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fees.bursaryaward')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fees.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fees.feeinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('applies_to', models.CharField(choices=[('all', 'All students'), ('day', 'Day scholars'), ('boarder', 'Boarders')], default='all', max_length=10)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.academicyear')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='fees.feecategory')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.grade')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.term')),
            ],
            options={
                'ordering': ['term__start_date', 'grade__level'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('ecocash', 'EcoCash'), ('card', 'Card'), ('cheque', 'Cheque')], default='cash', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], default='posted', max_length=10)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounting.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal')),
                ('payer_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fx_difference_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.feeinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.receipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['status', 'due_date'], name='fees_feeinv_status_dc1d90_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['student', 'date'], name='fees_feeinv_student_86d395_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['currency', 'status'], name='fees_feeinv_currenc_d362d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('billing_run__isnull', False)), fields=('billing_run', 'student'), name='unique_invoice_per_run_per_student'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('term', 'grade', 'fee_category', 'currency', 'applies_to')},
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['student', 'date'], name='fees_receip_student_822740_idx'),
        ),
    ]
