# Generated by Django 5.2.16 on 2026-07-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_tenancy'),
        ('students', '0002_tenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrun',
            name='classes',
            field=models.ManyToManyField(blank=True, to='students.classroom'),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='scope',
            field=models.CharField(choices=[('whole_school', 'Whole school'), ('grades', 'Grades'), ('classes', 'Classes'), ('students', 'Students')], default='grades', max_length=15),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.student'),
        ),
    ]
