# Generated by Django 5.2.16 on 2026-07-30 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('vendor_bill', 'Vendor bill'), ('fee_receipt', 'Fee receipt'), ('expense', 'Expense'), ('other', 'Other / unknown')], db_index=True, default='other', max_length=20)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('email', 'Email'), ('api', 'API')], default='upload', max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('extracted', 'Extracted'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected')], db_index=True, default='received', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='ingestion/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('raw_text', models.TextField(blank=True)),
                ('extraction', models.JSONField(blank=True, default=dict)),
                ('proposed', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('target_currency', models.CharField(default='USD', max_length=3)),
                ('posted_document_type', models.CharField(blank=True, max_length=50)),
                ('posted_document_id', models.CharField(blank=True, max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_items', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'doc_type'], name='ingestion_i_status_6e41fe_idx')],
            },
        ),
    ]
