# Generated by Django 5.2.16 on 2026-07-31 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_reorder_qty_item_track_lots_stockrequisition_and_more'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interschooltransfer',
            name='from_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='interschooltransfer',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='interschooltransfer',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='interschooltransfer',
            name='to_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='interschooltransfer',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='interschooltransfer',
            name='kind',
            field=models.CharField(choices=[('funds', 'Funds'), ('student', 'Student'), ('stock', 'Stock')], max_length=10),
        ),
    ]
